# Generated by Django 6.0 on 2025-12-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('rok', models.IntegerField()),
                ('cena_za_dzien', models.IntegerField()),
                ('dostepnosc', models.BooleanField(default=True)),
                ('opis', models.TextField()),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_od', models.DateField()),
                ('data_do', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana')], default='pending', max_length=20)),
                ('cena_ogolna', models.FloatField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.samochod')),
            ],
        ),
    ]
