# Generated by Django 6.0 on 2025-12-22 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samochod',
            name='dostepnosc',
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='appointments.samochod'),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='cena_ogolna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='samochod',
            name='cena_za_dzien',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
