# Generated by Django 6.0 on 2025-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_samochod_dostepnosc_alter_rezerwacja_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samochod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
